"""
Kareer Kranti Roadmap Configuration & Reference Layer.

Uses roadmap.sh as the external roadmap reference layer.
Contains maintainable static mappings without dynamic scraping.
"""

from typing import Dict, List, Any

OFFICIAL_ROLE_ROADMAPS: Dict[str, Dict[str, Any]] = {
    "Software Engineer": {
        "primary": {
            "name": "Full Stack Developer",
            "url": "https://roadmap.sh/full-stack",
            "description": "Full stack development pathway covering modern frontend, backend systems, databases, and deployment.",
        },
        "supporting": [
            {"name": "Backend", "url": "https://roadmap.sh/backend"},
            {"name": "Data Structures & Algorithms", "url": "https://roadmap.sh/datastructures-and-algorithms"},
            {"name": "SQL", "url": "https://roadmap.sh/sql"},
            {"name": "Git and GitHub", "url": "https://roadmap.sh/git-github"},
            {"name": "Docker", "url": "https://roadmap.sh/docker"},
            {"name": "System Design", "url": "https://roadmap.sh/system-design"},
            {"name": "API Design", "url": "https://roadmap.sh/api-design"},
        ],
    },
    "Frontend Developer": {
        "primary": {
            "name": "Frontend Developer",
            "url": "https://roadmap.sh/frontend",
            "description": "Client-side engineering, modern component architecture, state management, and responsive web design.",
        },
        "supporting": [
            {"name": "JavaScript", "url": "https://roadmap.sh/javascript"},
            {"name": "TypeScript", "url": "https://roadmap.sh/typescript"},
            {"name": "React", "url": "https://roadmap.sh/react"},
            {"name": "Git and GitHub", "url": "https://roadmap.sh/git-github"},
            {"name": "API Design", "url": "https://roadmap.sh/api-design"},
        ],
    },
    "Data Scientist": {
        "primary": {
            "name": "AI & Data Scientist",
            "url": "https://roadmap.sh/ai-data-scientist",
            "description": "Statistical modeling, exploratory data analysis, machine learning pipelines, and model evaluation.",
        },
        "supporting": [
            {"name": "Python", "url": "https://roadmap.sh/python"},
            {"name": "Python for Data Analysis", "url": "https://roadmap.sh/python-data-analysis"},
            {"name": "SQL", "url": "https://roadmap.sh/sql"},
            {"name": "Machine Learning", "url": "https://roadmap.sh/machine-learning"},
            {"name": "Data Structures & Algorithms", "url": "https://roadmap.sh/datastructures-and-algorithms"},
        ],
    },
    "Data Analyst": {
        "primary": {
            "name": "Data Analyst",
            "url": "https://roadmap.sh/data-analyst",
            "description": "Data wrangling, SQL querying, business intelligence, dashboarding, and actionable data communication.",
        },
        "supporting": [
            {"name": "SQL", "url": "https://roadmap.sh/sql"},
            {"name": "Python", "url": "https://roadmap.sh/python"},
            {"name": "Python for Data Analysis", "url": "https://roadmap.sh/python-data-analysis"},
            {"name": "Tableau / Power BI", "url": "https://roadmap.sh/data-analyst"},
        ],
    },
    "AI Engineer": {
        "primary": {
            "name": "AI Engineer",
            "url": "https://roadmap.sh/ai-engineer",
            "description": "Applied artificial intelligence, LLMs, neural networks, ML engineering, and scalable AI service APIs.",
        },
        "supporting": [
            {"name": "Python", "url": "https://roadmap.sh/python"},
            {"name": "Machine Learning", "url": "https://roadmap.sh/machine-learning"},
            {"name": "Docker", "url": "https://roadmap.sh/docker"},
            {"name": "API Design", "url": "https://roadmap.sh/api-design"},
        ],
    },
    "UI/UX Designer": {
        "primary": {
            "name": "UX Design",
            "url": "https://roadmap.sh/ux-design",
            "description": "User-centered design, wireframing, high-fidelity prototyping, user research, and interactive design systems.",
        },
        "supporting": [
            {"name": "Design System", "url": "https://roadmap.sh/design-system"},
            {"name": "Frontend Basics", "url": "https://roadmap.sh/frontend"},
        ],
    },
    "DevOps": {
        "primary": {
            "name": "DevOps Engineer",
            "url": "https://roadmap.sh/devops",
            "description": "Continuous integration & continuous delivery, containerization, cloud infrastructure, and observability.",
        },
        "supporting": [
            {"name": "Docker", "url": "https://roadmap.sh/docker"},
            {"name": "Kubernetes", "url": "https://roadmap.sh/kubernetes"},
            {"name": "AWS", "url": "https://roadmap.sh/aws"},
            {"name": "Linux", "url": "https://roadmap.sh/linux"},
            {"name": "Git and GitHub", "url": "https://roadmap.sh/git-github"},
        ],
    },
}

SKILL_ROADMAP_URLS: Dict[str, str] = {
    "Python": "https://roadmap.sh/python",
    "Python for Data Analysis": "https://roadmap.sh/python-data-analysis",
    "SQL": "https://roadmap.sh/sql",
    "Java": "https://roadmap.sh/java",
    "JavaScript": "https://roadmap.sh/javascript",
    "TypeScript": "https://roadmap.sh/typescript",
    "React": "https://roadmap.sh/react",
    "Node.js": "https://roadmap.sh/nodejs",
    "Flutter": "https://roadmap.sh/flutter",
    "Machine Learning": "https://roadmap.sh/machine-learning",
    "Deep Learning": "https://roadmap.sh/machine-learning",
    "PyTorch": "https://roadmap.sh/machine-learning",
    "TensorFlow": "https://roadmap.sh/machine-learning",
    "Data Structures & Algorithms": "https://roadmap.sh/datastructures-and-algorithms",
    "Git": "https://roadmap.sh/git-github",
    "GitHub": "https://roadmap.sh/git-github",
    "CI/CD": "https://roadmap.sh/devops",
    "Docker": "https://roadmap.sh/docker",
    "Kubernetes": "https://roadmap.sh/kubernetes",
    "AWS": "https://roadmap.sh/aws",
    "System Design": "https://roadmap.sh/system-design",
    "API Design": "https://roadmap.sh/api-design",
    "REST API": "https://roadmap.sh/api-design",
    "Design System": "https://roadmap.sh/design-system",
    "Linux": "https://roadmap.sh/linux",
    "MongoDB": "https://roadmap.sh/mongodb",
    "Redis": "https://roadmap.sh/redis",
    "PostgreSQL": "https://roadmap.sh/sql",
    "MySQL": "https://roadmap.sh/sql",
    "UX Design": "https://roadmap.sh/ux-design",
    "UI Design": "https://roadmap.sh/ux-design",
    "Figma": "https://roadmap.sh/ux-design",
    "HTML": "https://roadmap.sh/frontend",
    "CSS": "https://roadmap.sh/frontend",
    "Tailwind CSS": "https://roadmap.sh/frontend",
    "Data Analysis": "https://roadmap.sh/data-analyst",
    "Pandas": "https://roadmap.sh/python-data-analysis",
    "NumPy": "https://roadmap.sh/python-data-analysis",
    "Testing": "https://roadmap.sh/backend",
}

# Curated role milestones with explicit prerequisite dependency graph
ROLE_MILESTONES: Dict[str, List[Dict[str, Any]]] = {
    "Software Engineer": [
        {
            "id": "swe-git",
            "name": "Git & GitHub Version Control",
            "roadmap": "full-stack",
            "related_skills": ["Git", "GitHub"],
            "prerequisites": [],
            "source_url": "https://roadmap.sh/git-github",
            "recommended_artifact": "Publish a clean GitHub repository with atomic commits, branch workflows, and PR history.",
            "expected_proof": "GitHub repo commits, commit frequency, and branch history.",
            "why_it_matters": "Essential collaboration and code versioning baseline across all software teams.",
            "importance": 0.85,
        },
        {
            "id": "swe-backend-core",
            "name": "Backend Language & Logic (Python / Java / Go)",
            "roadmap": "full-stack",
            "related_skills": ["Python", "Java", "Go", "C++", "C#"],
            "prerequisites": ["swe-git"],
            "source_url": "https://roadmap.sh/backend",
            "recommended_artifact": "Implement core backend business logic with modular architecture and clean functions.",
            "expected_proof": "Source code files (.py, .java, .go) with meaningful LOC and algorithmic depth.",
            "why_it_matters": "Core implementation language demonstrating fundamental software engineering competence.",
            "importance": 0.95,
        },
        {
            "id": "swe-rest-api",
            "name": "REST API & Web Frameworks",
            "roadmap": "full-stack",
            "related_skills": ["REST API", "FastAPI", "Django", "Flask", "Express.js", "API Design"],
            "prerequisites": ["swe-backend-core"],
            "source_url": "https://roadmap.sh/api-design",
            "recommended_artifact": "Build structured HTTP endpoints with validation, serialization, and status codes.",
            "expected_proof": "Route definitions, controller files, OpenAPI/Swagger specifications.",
            "why_it_matters": "Standard communication interface for modern distributed services and client apps.",
            "importance": 0.90,
        },
        {
            "id": "swe-database",
            "name": "Relational Databases & SQL Modeling",
            "roadmap": "full-stack",
            "related_skills": ["SQL", "PostgreSQL", "MySQL", "Database"],
            "prerequisites": ["swe-backend-core"],
            "source_url": "https://roadmap.sh/sql",
            "recommended_artifact": "Design normalized database schema with migration scripts and indexed queries.",
            "expected_proof": "SQL schema files, migration files, ORM models (SQLAlchemy/Prisma), query definitions.",
            "why_it_matters": "Reliable transactional data storage and efficient relational query execution.",
            "importance": 0.85,
        },
        {
            "id": "swe-testing",
            "name": "Automated Testing & Quality",
            "roadmap": "full-stack",
            "related_skills": ["Testing"],
            "prerequisites": ["swe-rest-api"],
            "source_url": "https://roadmap.sh/backend",
            "recommended_artifact": "Add automated unit and integration tests with pytest or jest achieving test suite coverage.",
            "expected_proof": "Test files (test_*.py, *.test.ts), assertions, test directory structure.",
            "why_it_matters": "Guarantees regression resistance, maintainability, and production confidence.",
            "importance": 0.80,
        },
        {
            "id": "swe-docker",
            "name": "Containerization (Docker)",
            "roadmap": "full-stack",
            "related_skills": ["Docker"],
            "prerequisites": ["swe-rest-api"],
            "source_url": "https://roadmap.sh/docker",
            "recommended_artifact": "Dockerize an existing project with a multi-stage Dockerfile and docker-compose.yml.",
            "expected_proof": "Dockerfile, docker-compose.yml, container build definitions.",
            "why_it_matters": "Ensures reproducible environments across development, testing, and production.",
            "importance": 0.75,
        },
        {
            "id": "swe-cicd",
            "name": "CI/CD Automation Pipelines",
            "roadmap": "full-stack",
            "related_skills": ["CI/CD"],
            "prerequisites": ["swe-testing", "swe-docker"],
            "source_url": "https://roadmap.sh/devops",
            "recommended_artifact": "Create GitHub Actions workflow YAML running linting, automated tests, and Docker builds.",
            "expected_proof": ".github/workflows/*.yml workflow files with build and test steps.",
            "why_it_matters": "Automates validation and continuous delivery for enterprise development.",
            "importance": 0.70,
        },
        {
            "id": "swe-dsa",
            "name": "Data Structures & Algorithms",
            "roadmap": "full-stack",
            "related_skills": ["Data Structures & Algorithms"],
            "prerequisites": ["swe-backend-core"],
            "source_url": "https://roadmap.sh/datastructures-and-algorithms",
            "recommended_artifact": "Implement efficient algorithmic solutions (trees, graphs, DP) with complexity analysis.",
            "expected_proof": "Implementation files with algorithmic structures and complexity considerations.",
            "why_it_matters": "Critical foundation for technical problem-solving and optimization in scale engineering.",
            "importance": 0.75,
        },
        {
            "id": "swe-system-design",
            "name": "System Design & Architecture",
            "roadmap": "full-stack",
            "related_skills": ["System Design", "Redis"],
            "prerequisites": ["swe-database", "swe-docker"],
            "source_url": "https://roadmap.sh/system-design",
            "recommended_artifact": "Document a scalable architecture design with caching layer (Redis), async workers, and load boundaries.",
            "expected_proof": "Architecture specifications, caching integration, asynchronous queue implementations.",
            "why_it_matters": "Key determinant of scaling capability, fault tolerance, and system performance.",
            "importance": 0.70,
        },
        {
            "id": "swe-kubernetes",
            "name": "Container Orchestration (Kubernetes)",
            "roadmap": "full-stack",
            "related_skills": ["Kubernetes"],
            "prerequisites": ["swe-docker", "swe-cicd"],
            "source_url": "https://roadmap.sh/kubernetes",
            "recommended_artifact": "Author Kubernetes manifest deployment files (Deployments, Services, ConfigMaps).",
            "expected_proof": "Kubernetes manifest YAML files (k8s/ or helm charts).",
            "why_it_matters": "Industry standard for resilient cloud-native workload orchestration.",
            "importance": 0.50,
        },
    ],

    "Frontend Developer": [
        {
            "id": "fe-html-css",
            "name": "Semantic HTML & Responsive CSS",
            "roadmap": "frontend",
            "related_skills": ["HTML", "CSS", "Tailwind CSS"],
            "prerequisites": [],
            "source_url": "https://roadmap.sh/frontend",
            "recommended_artifact": "Build accessible, responsive page layouts with semantic HTML5 and modern CSS/Tailwind.",
            "expected_proof": "HTML/CSS stylesheets, layout templates, responsive styling classes.",
            "why_it_matters": "Core foundational building blocks for all web interfaces.",
            "importance": 0.90,
        },
        {
            "id": "fe-javascript",
            "name": "JavaScript Modern Fundamentals",
            "roadmap": "frontend",
            "related_skills": ["JavaScript"],
            "prerequisites": ["fe-html-css"],
            "source_url": "https://roadmap.sh/javascript",
            "recommended_artifact": "Write modular ES6+ JavaScript code utilizing async/await, DOM APIs, and closures.",
            "expected_proof": "JavaScript source files (.js/.mjs) with DOM manipulation or client logic.",
            "why_it_matters": "Dynamic behavior and interactivity execution runtime for browsers.",
            "importance": 0.95,
        },
        {
            "id": "fe-git",
            "name": "Git & GitHub Workflow",
            "roadmap": "frontend",
            "related_skills": ["Git", "GitHub"],
            "prerequisites": [],
            "source_url": "https://roadmap.sh/git-github",
            "recommended_artifact": "Maintain clean frontend codebases with structured commits and semantic versioning.",
            "expected_proof": "GitHub repo commits and project history.",
            "why_it_matters": "Essential for collaboration and code history tracking.",
            "importance": 0.80,
        },
        {
            "id": "fe-typescript",
            "name": "TypeScript Type Safety",
            "roadmap": "frontend",
            "related_skills": ["TypeScript"],
            "prerequisites": ["fe-javascript"],
            "source_url": "https://roadmap.sh/typescript",
            "recommended_artifact": "Type your frontend applications with strict interfaces, generics, and compiler configurations.",
            "expected_proof": "TypeScript files (.ts, .tsx) and tsconfig.json.",
            "why_it_matters": "Prevents runtime type errors and dramatically scales frontend development reliability.",
            "importance": 0.85,
        },
        {
            "id": "fe-react",
            "name": "React & Component Architecture",
            "roadmap": "frontend",
            "related_skills": ["React", "Next.js"],
            "prerequisites": ["fe-javascript", "fe-typescript"],
            "source_url": "https://roadmap.sh/react",
            "recommended_artifact": "Build component-driven single-page or SSR application using custom hooks and state management.",
            "expected_proof": "React JSX/TSX component files, hooks, package.json with react dependencies.",
            "why_it_matters": "Dominant ecosystem standard for building enterprise web applications.",
            "importance": 0.95,
        },
        {
            "id": "fe-api",
            "name": "API Consumption & State Management",
            "roadmap": "frontend",
            "related_skills": ["REST API", "GraphQL", "API Design"],
            "prerequisites": ["fe-react"],
            "source_url": "https://roadmap.sh/api-design",
            "recommended_artifact": "Implement async data-fetching patterns with caching, optimistic updates, and error boundaries.",
            "expected_proof": "Fetch/axios/swr/tanstack-query integration, error handling logic.",
            "why_it_matters": "Enables seamless connection between client UI and backend data services.",
            "importance": 0.85,
        },
        {
            "id": "fe-testing",
            "name": "Frontend Testing & Quality",
            "roadmap": "frontend",
            "related_skills": ["Testing"],
            "prerequisites": ["fe-react"],
            "source_url": "https://roadmap.sh/frontend",
            "recommended_artifact": "Write unit and component tests using Jest/React Testing Library.",
            "expected_proof": "Test files (.test.tsx, .spec.ts), component render test coverage.",
            "why_it_matters": "Prevents UI regressions and validates user interaction flows.",
            "importance": 0.75,
        },
    ],

    "Data Scientist": [
        {
            "id": "ds-python",
            "name": "Python for Data Science",
            "roadmap": "ai-data-scientist",
            "related_skills": ["Python"],
            "prerequisites": [],
            "source_url": "https://roadmap.sh/python",
            "recommended_artifact": "Write computational Python code for data processing and mathematical modeling.",
            "expected_proof": "Python scripts and Jupyter notebooks with algorithmic data logic.",
            "why_it_matters": "Primary language for data science and statistical computing worldwide.",
            "importance": 0.95,
        },
        {
            "id": "ds-analysis",
            "name": "Data Wrangling (Pandas & NumPy)",
            "roadmap": "ai-data-scientist",
            "related_skills": ["Pandas", "NumPy", "Data Analysis"],
            "prerequisites": ["ds-python"],
            "source_url": "https://roadmap.sh/python-data-analysis",
            "recommended_artifact": "Perform end-to-end data cleaning, aggregations, feature engineering, and statistical analysis.",
            "expected_proof": "Pandas/NumPy code, dataframe transformations, exploratory data notebooks.",
            "why_it_matters": "Data preparation represents the vast majority of real-world data science pipelines.",
            "importance": 0.90,
        },
        {
            "id": "ds-sql",
            "name": "SQL & Relational Data Extraction",
            "roadmap": "ai-data-scientist",
            "related_skills": ["SQL", "PostgreSQL"],
            "prerequisites": [],
            "source_url": "https://roadmap.sh/sql",
            "recommended_artifact": "Write analytical SQL queries with CTEs, window functions, and multi-table joins.",
            "expected_proof": "SQL query files, analytical database schemas.",
            "why_it_matters": "Required to query corporate data warehouses and extract training datasets.",
            "importance": 0.85,
        },
        {
            "id": "ds-ml",
            "name": "Machine Learning Foundations (Scikit-Learn)",
            "roadmap": "ai-data-scientist",
            "related_skills": ["Machine Learning", "Scikit-learn"],
            "prerequisites": ["ds-python", "ds-analysis"],
            "source_url": "https://roadmap.sh/machine-learning",
            "recommended_artifact": "Train, tune hyperparameters, and evaluate classification or regression ML models.",
            "expected_proof": "Model training scripts, cross-validation code, evaluation metric charts.",
            "why_it_matters": "Core discipline for predictive modeling, clustering, and decision intelligence.",
            "importance": 0.90,
        },
        {
            "id": "ds-deep-learning",
            "name": "Deep Learning & Neural Networks (PyTorch / TensorFlow)",
            "roadmap": "ai-data-scientist",
            "related_skills": ["Deep Learning", "PyTorch", "TensorFlow"],
            "prerequisites": ["ds-ml"],
            "source_url": "https://roadmap.sh/machine-learning",
            "recommended_artifact": "Train neural network architecture for NLP or Computer Vision with loss tracking.",
            "expected_proof": "PyTorch/TensorFlow training loops, model weight definitions.",
            "why_it_matters": "Drives modern advances in image, speech, and generative AI models.",
            "importance": 0.75,
        },
        {
            "id": "ds-dsa",
            "name": "Data Structures & Algorithms",
            "roadmap": "ai-data-scientist",
            "related_skills": ["Data Structures & Algorithms"],
            "prerequisites": ["ds-python"],
            "source_url": "https://roadmap.sh/datastructures-and-algorithms",
            "recommended_artifact": "Optimize algorithmic time and space complexity for large-scale data processing.",
            "expected_proof": "Algorithmic implementations and efficiency optimizations.",
            "why_it_matters": "Ensures scalable data processing pipelines without computational bottlenecks.",
            "importance": 0.70,
        },
    ],

    "Data Analyst": [
        {
            "id": "da-sql",
            "name": "Advanced SQL & Database Analysis",
            "roadmap": "data-analyst",
            "related_skills": ["SQL", "PostgreSQL", "MySQL"],
            "prerequisites": [],
            "source_url": "https://roadmap.sh/sql",
            "recommended_artifact": "Author complex analytical queries with window functions, aggregations, and subqueries.",
            "expected_proof": "SQL files (.sql), query scripts, analytical table definitions.",
            "why_it_matters": "The single most important skill for querying relational data warehouses.",
            "importance": 0.95,
        },
        {
            "id": "da-python",
            "name": "Python & Pandas for Data Analysis",
            "roadmap": "data-analyst",
            "related_skills": ["Python", "Pandas", "NumPy", "Data Analysis"],
            "prerequisites": [],
            "source_url": "https://roadmap.sh/python-data-analysis",
            "recommended_artifact": "Build data cleaning scripts and exploratory analyses on raw datasets.",
            "expected_proof": "Jupyter notebooks, Pandas scripts, data cleaning pipelines.",
            "why_it_matters": "Allows automated statistical analysis and flexible data manipulation beyond SQL.",
            "importance": 0.90,
        },
        {
            "id": "da-bi",
            "name": "Business Intelligence & Visualization",
            "roadmap": "data-analyst",
            "related_skills": ["Power BI", "Tableau", "Data Analysis"],
            "prerequisites": ["da-sql"],
            "source_url": "https://roadmap.sh/data-analyst",
            "recommended_artifact": "Create interactive dashboards with KPI metrics, drill-down charts, and executive insights.",
            "expected_proof": "Dashboard screenshots, exported reports, BI data model definitions.",
            "why_it_matters": "Transforms raw metrics into clear visual narratives for business decision-makers.",
            "importance": 0.85,
        },
        {
            "id": "da-git",
            "name": "Version Control & Reporting Workflow",
            "roadmap": "data-analyst",
            "related_skills": ["Git", "GitHub"],
            "prerequisites": [],
            "source_url": "https://roadmap.sh/git-github",
            "recommended_artifact": "Version control analytical scripts and reproduce report generation workflows.",
            "expected_proof": "Repository commits, reproducible run scripts, README documentation.",
            "why_it_matters": "Ensures reproducibility and auditability of analytical findings.",
            "importance": 0.70,
        },
    ],

    "AI Engineer": [
        {
            "id": "ai-python",
            "name": "Advanced Python & Asynchronous Systems",
            "roadmap": "ai-engineer",
            "related_skills": ["Python"],
            "prerequisites": [],
            "source_url": "https://roadmap.sh/python",
            "recommended_artifact": "Implement async Python pipelines with type hints and robust exception handling.",
            "expected_proof": "Python source code with async coroutines, typing, and structural patterns.",
            "why_it_matters": "Core runtime language for modern AI orchestration and model inference servers.",
            "importance": 0.95,
        },
        {
            "id": "ai-ml-frameworks",
            "name": "Machine Learning & Deep Learning (PyTorch / Scikit-Learn)",
            "roadmap": "ai-engineer",
            "related_skills": ["Machine Learning", "PyTorch", "TensorFlow", "Scikit-learn"],
            "prerequisites": ["ai-python"],
            "source_url": "https://roadmap.sh/machine-learning",
            "recommended_artifact": "Implement model evaluation, fine-tuning, embeddings generation, or inference pipelines.",
            "expected_proof": "PyTorch/Scikit-learn training or inference scripts, tensor operations.",
            "why_it_matters": "Essential for training, modifying, and evaluating specialized AI models.",
            "importance": 0.90,
        },
        {
            "id": "ai-nlp",
            "name": "NLP & Large Language Models",
            "roadmap": "ai-engineer",
            "related_skills": ["NLP"],
            "prerequisites": ["ai-python", "ai-ml-frameworks"],
            "source_url": "https://roadmap.sh/ai-engineer",
            "recommended_artifact": "Build LLM applications with prompt evaluation, retrieval augmented generation (RAG), or vector search.",
            "expected_proof": "RAG pipeline code, prompt templates, vector database integration.",
            "why_it_matters": "The core of modern AI application development and generative AI solutions.",
            "importance": 0.90,
        },
        {
            "id": "ai-api",
            "name": "AI Microservice & API Design",
            "roadmap": "ai-engineer",
            "related_skills": ["REST API", "FastAPI", "API Design"],
            "prerequisites": ["ai-python"],
            "source_url": "https://roadmap.sh/api-design",
            "recommended_artifact": "Wrap ML/AI models in high-throughput FastAPI endpoints with streaming and schema validation.",
            "expected_proof": "FastAPI/Flask API routes, streaming responses, input validation models.",
            "why_it_matters": "Exposes model capabilities to web, mobile, and enterprise consumers reliably.",
            "importance": 0.85,
        },
        {
            "id": "ai-docker",
            "name": "Containerization & Deployment (Docker)",
            "roadmap": "ai-engineer",
            "related_skills": ["Docker"],
            "prerequisites": ["ai-api"],
            "source_url": "https://roadmap.sh/docker",
            "recommended_artifact": "Containerize AI application with CUDA/CPU environment in a reproducible Docker image.",
            "expected_proof": "Dockerfile with environment dependencies, compose definitions.",
            "why_it_matters": "Prevents environment drift and ensures seamless deployment across cloud GPUs.",
            "importance": 0.80,
        },
    ],

    "UI/UX Designer": [
        {
            "id": "ux-research",
            "name": "User Research & Information Architecture",
            "roadmap": "ux-design",
            "related_skills": ["UX Design"],
            "prerequisites": [],
            "source_url": "https://roadmap.sh/ux-design",
            "recommended_artifact": "Document user personas, journey maps, and information architecture hierarchy.",
            "expected_proof": "Case study documentation, wireframes, user testing summaries in portfolio.",
            "why_it_matters": "Ensures design solutions solve real user pain points backed by evidence.",
            "importance": 0.90,
        },
        {
            "id": "ux-figma",
            "name": "Figma & Interactive Prototyping",
            "roadmap": "ux-design",
            "related_skills": ["Figma", "UI Design", "Adobe XD"],
            "prerequisites": ["ux-research"],
            "source_url": "https://roadmap.sh/ux-design",
            "recommended_artifact": "Create high-fidelity interactive Figma prototype with responsive layouts and component variants.",
            "expected_proof": "Figma project links, interactive prototype cases, visual case studies.",
            "why_it_matters": "Industry benchmark tool for interface crafting and user testing.",
            "importance": 0.95,
        },
        {
            "id": "ux-design-system",
            "name": "Design Systems & Token Architecture",
            "roadmap": "ux-design",
            "related_skills": ["Design System"],
            "prerequisites": ["ux-figma"],
            "source_url": "https://roadmap.sh/design-system",
            "recommended_artifact": "Construct scalable design system with typography scale, color tokens, and reusable components.",
            "expected_proof": "Design system documentation, component libraries, typography/color tokens.",
            "why_it_matters": "Maintains visual consistency and speeds up development across engineering teams.",
            "importance": 0.85,
        },
        {
            "id": "ux-frontend",
            "name": "Frontend Basics (HTML / CSS)",
            "roadmap": "ux-design",
            "related_skills": ["HTML", "CSS", "Tailwind CSS"],
            "prerequisites": ["ux-figma"],
            "source_url": "https://roadmap.sh/frontend",
            "recommended_artifact": "Translate Figma designs into responsive HTML/CSS markup with accessible semantic structure.",
            "expected_proof": "HTML/CSS implementation files, code sandbox/demo links.",
            "why_it_matters": "Bridges the gap between designers and software engineers for seamless handoff.",
            "importance": 0.70,
        },
    ],

    "DevOps": [
        {
            "id": "devops-git",
            "name": "Git & GitHub Version Control",
            "roadmap": "devops",
            "related_skills": ["Git", "GitHub"],
            "prerequisites": [],
            "source_url": "https://roadmap.sh/git-github",
            "recommended_artifact": "Implement branch protection, commit signing, and tag release automation.",
            "expected_proof": "GitHub repo configurations, release tags, commit history.",
            "why_it_matters": "Foundation for GitOps and continuous infrastructure management.",
            "importance": 0.85,
        },
        {
            "id": "devops-linux",
            "name": "Linux & Shell Scripting",
            "roadmap": "devops",
            "related_skills": ["Linux", "Bash"],
            "prerequisites": [],
            "source_url": "https://roadmap.sh/linux",
            "recommended_artifact": "Author robust Bash/shell scripts for system automation and log processing.",
            "expected_proof": "Shell scripts (.sh), system configurations.",
            "why_it_matters": "The operating system foundation for server infrastructure and containers.",
            "importance": 0.90,
        },
        {
            "id": "devops-docker",
            "name": "Containerization (Docker)",
            "roadmap": "devops",
            "related_skills": ["Docker"],
            "prerequisites": ["devops-linux"],
            "source_url": "https://roadmap.sh/docker",
            "recommended_artifact": "Create optimized multi-stage container builds with minimal attack surface.",
            "expected_proof": "Dockerfile, compose files, container scan results.",
            "why_it_matters": "Enables reproducible deployments across diverse cloud environments.",
            "importance": 0.95,
        },
        {
            "id": "devops-cicd",
            "name": "CI/CD Pipeline Automation",
            "roadmap": "devops",
            "related_skills": ["CI/CD"],
            "prerequisites": ["devops-git", "devops-docker"],
            "source_url": "https://roadmap.sh/devops",
            "recommended_artifact": "Build multi-stage GitHub Actions CI/CD pipeline with automated testing, linting, and image push.",
            "expected_proof": ".github/workflows/*.yml files.",
            "why_it_matters": "Accelerates safe delivery and eliminates manual release toil.",
            "importance": 0.95,
        },
        {
            "id": "devops-k8s",
            "name": "Container Orchestration (Kubernetes)",
            "roadmap": "devops",
            "related_skills": ["Kubernetes"],
            "prerequisites": ["devops-docker", "devops-cicd"],
            "source_url": "https://roadmap.sh/kubernetes",
            "recommended_artifact": "Deploy production-grade Kubernetes manifests or Helm charts with health probes.",
            "expected_proof": "Kubernetes YAML manifests, Helm charts.",
            "why_it_matters": "Enterprise platform for scaling, self-healing, and traffic routing.",
            "importance": 0.85,
        },
        {
            "id": "devops-cloud",
            "name": "Cloud Infrastructure (AWS)",
            "roadmap": "devops",
            "related_skills": ["AWS"],
            "prerequisites": ["devops-linux"],
            "source_url": "https://roadmap.sh/aws",
            "recommended_artifact": "Provision and document cloud resources (compute, storage, VPC networks).",
            "expected_proof": "CloudFormation / Terraform / cloud architecture configurations.",
            "why_it_matters": "Powers modern scalable cloud-native architectures.",
            "importance": 0.80,
        },
    ],
}
