"""
Production Ownership Map Service.

Deterministically computes full-history Git blame ownership attribution
for a single GitHub repository using safe bare clones.
"""

import math
import re
import shutil
import tempfile
import time
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

import structlog

from app.core.config import settings
from app.services.analysis.skill_normaliser import SkillNormaliser
from app.services.ownership.git_blame_runner import GitBlameRunner
from app.services.ownership.identity_resolver import IdentityResolver
from app.services.ownership.models import (
    AuthorCategory,
    FileOwnershipResult,
    LineRange,
    OwnershipAnalysisResult,
    SkillOwnershipResult,
    StudentIdentity,
)

log = structlog.get_logger(__name__)

# Strict repository identifier regex
REPO_NAME_REGEX = re.compile(r"^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$")

# Hard resource limits
MAX_CLONE_MB = getattr(settings, "GITHUB_MAX_CLONE_MB", 50)
MAX_SOURCE_FILES = 400
MAX_COMMITS = 3000
MAX_FILE_SIZE_BYTES = 300 * 1024  # 300 KB
MAX_FILE_BLAME_TIMEOUT_SEC = 20
MAX_REPO_TIMEOUT_SEC = 90
MAX_LINE_LENGTH = 1000
MAX_AVG_LINE_LENGTH = 200
MIN_RANGE_SIZE = 10

# Supported source code extensions
SOURCE_EXTENSIONS: Set[str] = {
    ".py", ".js", ".jsx", ".ts", ".tsx", ".java", ".go", ".rs",
    ".c", ".cpp", ".h", ".hpp", ".cs", ".rb", ".php", ".kt",
    ".swift", ".sql", ".sh", ".bash", ".html", ".css", ".scss",
    ".sass", ".vue", ".svelte", ".scala", ".m", ".r"
}

# Directories to ignore
EXCLUDED_DIR_PATTERNS: Set[str] = {
    "node_modules", "vendor", "dist", "build", "out", ".next",
    "target", "__pycache__", "venv", ".venv", "env", ".env",
    "coverage", "third_party", ".git", ".idea", ".vscode"
}

# File patterns to exclude
EXCLUDED_FILE_PATTERNS: List[re.Pattern] = [
    re.compile(r"package-lock\.json$", re.IGNORECASE),
    re.compile(r"yarn\.lock$", re.IGNORECASE),
    re.compile(r"pnpm-lock\.yaml$", re.IGNORECASE),
    re.compile(r"poetry\.lock$", re.IGNORECASE),
    re.compile(r"Gemfile\.lock$", re.IGNORECASE),
    re.compile(r"Cargo\.lock$", re.IGNORECASE),
    re.compile(r"\.lock$", re.IGNORECASE),
    re.compile(r"\.min\.(js|css)$", re.IGNORECASE),
    re.compile(r"\.map$", re.IGNORECASE),
]

# Generated code header markers (in first 5 lines)
GENERATED_FILE_MARKERS = ["generated", "do not edit", "auto-generated", "autogenerated"]


# ── Pure Computation Helpers ─────────────────────────────────────────────────

def validate_repo_identifier(repo_identifier: str) -> bool:
    """Validate that repository identifier strictly matches 'owner/repo' format."""
    if not repo_identifier or not isinstance(repo_identifier, str):
        return False
    return bool(REPO_NAME_REGEX.match(repo_identifier.strip()))


def is_meaningful_line(line: str, extension: str) -> bool:
    """
    Check if a line contains meaningful code (not blank, not comment-only,
    not a lone bracket or formatting syntax).
    """
    stripped = line.strip()
    if not stripped:
        return False

    # Ignore lone structural punctuation / brackets
    if stripped in {
        "{", "}", "(", ")", "[", "]", ";", ",",
        "};", "});", "],", "),", "()", "{}", "[]", "};",
    }:
        return False

    ext = extension.lower()

    # Hash comments: Python, Shell, Ruby, YAML, Docker
    if ext in {".py", ".sh", ".bash", ".rb", ".yaml", ".yml", "dockerfile"}:
        if stripped.startswith("#"):
            return False
        if stripped in {'"""', "'''"} or stripped.startswith(('"""', "'''")):
            return False

    # C-style comments: JS, TS, Java, C, C++, Go, Rust, C#, PHP, Kotlin, Swift
    if ext in {
        ".js", ".jsx", ".ts", ".tsx", ".java", ".go", ".rs",
        ".c", ".cpp", ".h", ".hpp", ".cs", ".php", ".kt", ".swift"
    }:
        if (
            stripped.startswith("//")
            or stripped.startswith("/*")
            or stripped.startswith("*")
            or stripped.endswith("*/")
        ):
            return False

    # SQL comments
    if ext == ".sql":
        if (
            stripped.startswith("--")
            or stripped.startswith("/*")
            or stripped.startswith("*")
        ):
            return False

    # HTML / XML / Vue / Svelte comments
    if ext in {".html", ".xml", ".vue", ".svelte"}:
        if stripped.startswith("<!--") or stripped.endswith("-->"):
            return False

    return True


def should_skip_path(file_path: str) -> Tuple[bool, Optional[str]]:
    """
    Determine if a file path should be excluded based on directory or filename patterns.
    """
    p = Path(file_path)
    parts_lower = [part.lower() for part in p.parts]

    # Check directory segment exclusions
    for excluded_dir in EXCLUDED_DIR_PATTERNS:
        if excluded_dir in parts_lower[:-1]:
            return True, "excluded_path"

    filename = p.name.lower()

    # Check lockfiles and minified files
    for pattern in EXCLUDED_FILE_PATTERNS:
        if pattern.search(filename):
            return True, "excluded_lockfile_or_min"

    # Check supported extensions and special files
    ext = p.suffix.lower()
    is_docker = filename == "dockerfile" or filename.startswith("dockerfile.") or filename.startswith("docker-compose")
    is_workflow = ".github" in parts_lower and "workflows" in parts_lower
    is_supported = ext in SOURCE_EXTENSIONS or is_docker or is_workflow

    if not is_supported:
        return True, "unsupported_ext"

    return False, None


def check_generated_and_line_length(raw_lines: List[str]) -> Tuple[bool, Optional[str]]:
    """
    Inspect raw lines for:
    - Generated file markers in the first 5 lines
    - Extreme line length (average > 200 or any line > 1000 characters)
    """
    if not raw_lines:
        return False, None

    # Check first 5 lines for generated markers
    for line in raw_lines[:5]:
        line_lower = line.lower()
        for marker in GENERATED_FILE_MARKERS:
            if marker in line_lower:
                return True, "generated_file"

    # Check line lengths
    total_len = sum(len(line) for line in raw_lines)
    avg_len = total_len / len(raw_lines)
    if avg_len > MAX_AVG_LINE_LENGTH:
        return True, "extreme_avg_line_length"

    if any(len(line) > MAX_LINE_LENGTH for line in raw_lines):
        return True, "extreme_line_length"

    return False, None


# ── Ownership Service ────────────────────────────────────────────────────────

class OwnershipService:
    """
    Production service for computing safe, deterministic repository ownership maps.
    """

    def __init__(self, normaliser: Optional[SkillNormaliser] = None, github_token: Optional[str] = None):
        self.normaliser = normaliser or SkillNormaliser()
        self.github_token = github_token or settings.GITHUB_TOKEN

    def map_file_to_skills(self, file_path: str) -> List[str]:
        """
        Map a file path to canonical skill names using SkillNormaliser.
        """
        p = Path(file_path)
        ext = p.suffix.lower()
        filename = p.name.lower()
        path_lower = file_path.lower()
        skills: Set[str] = set()

        # 1. Extension to Primary Language
        ext_map = {
            ".py": "Python",
            ".ts": "TypeScript",
            ".tsx": "TypeScript",
            ".js": "JavaScript",
            ".jsx": "JavaScript",
            ".java": "Java",
            ".go": "Go",
            ".rs": "Rust",
            ".cpp": "C++",
            ".hpp": "C++",
            ".c": "C",
            ".h": "C",
            ".cs": "C#",
            ".rb": "Ruby",
            ".php": "PHP",
            ".kt": "Kotlin",
            ".swift": "Swift",
            ".sql": "SQL",
            ".sh": "Shell",
            ".bash": "Shell",
            ".html": "HTML",
            ".css": "CSS",
            ".scss": "SCSS",
            ".sass": "Sass",
            ".vue": "Vue",
            ".svelte": "Svelte",
            ".scala": "Scala",
        }
        if ext in ext_map:
            skills.add(self.normaliser.normalise(ext_map[ext]))

        # 2. Special Infrastructure Files
        if filename == "dockerfile" or filename.startswith("dockerfile.") or filename.startswith("docker-compose"):
            skills.add(self.normaliser.normalise("Docker"))

        if ".github/workflows" in path_lower:
            skills.add(self.normaliser.normalise("CI/CD"))

        # 3. Test Files
        if "test" in path_lower or "spec" in path_lower or "__tests__" in path_lower:
            skills.add(self.normaliser.normalise("Testing"))

        return sorted(list(skills))

    def evaluate_solo_repository_exception(
        self,
        repo_name: str,
        relation: str,
        student: StudentIdentity,
        commit_authors_summary: List[Tuple[str, str, str]]
    ) -> bool:
        """
        Narrow Solo-Owned Repository Exception:
        Applies if and only if ALL of the following are true:
        1. Student is owner of the repo (relation == 'owner' or repo starts with student_login/).
        2. Linked student non-bot commits >= 50% of total non-bot commits.
        3. No other single linked human represents > 10% of total non-bot commits.
        """
        repo_owner = repo_name.split("/")[0].strip().lower()
        login_lower = student.github_login.strip().lower()
        is_owner = (relation.lower() == "owner") or (repo_owner == login_lower)

        if not is_owner or not commit_authors_summary:
            return False

        student_commits = 0
        non_bot_commits = 0
        other_human_counts: Dict[str, int] = {}

        for sha, email, name in commit_authors_summary:
            cat = IdentityResolver.classify_author(email, name, student)
            if cat == AuthorCategory.BOT:
                continue

            non_bot_commits += 1
            if cat == AuthorCategory.STUDENT:
                student_commits += 1
            elif cat == AuthorCategory.OTHER_HUMAN:
                key = f"{name.strip().lower()}|{email.strip().lower()}"
                other_human_counts[key] = other_human_counts.get(key, 0) + 1

        if non_bot_commits == 0:
            return False

        # Condition 2: student commits >= 50%
        if (student_commits / non_bot_commits) < 0.50:
            return False

        # Condition 3: no other human > 10%
        for other_key, count in other_human_counts.items():
            if (count / non_bot_commits) > 0.10:
                return False

        return True

    def extract_top_ranges_for_skill(
        self,
        file_blames: List[Tuple[str, List[dict], List[float]]],
        target_skill: str,
        min_size: int = MIN_RANGE_SIZE,
        top_k: int = 5
    ) -> List[LineRange]:
        """
        Extract top contiguous student line ranges for a given skill across all analyzed files.
        A line is considered student-attributed if student share fraction >= 0.5.
        """
        ranges: List[LineRange] = []

        for file_path, blame_lines, student_shares in file_blames:
            skills = self.map_file_to_skills(file_path)
            if target_skill not in skills:
                continue

            current_start: Optional[int] = None
            current_end: Optional[int] = None
            current_count = 0

            for entry, s_share in zip(blame_lines, student_shares):
                line_no = entry.get("final_line_no", 0)
                is_student = s_share >= 0.5

                if is_student:
                    if current_start is None:
                        current_start = line_no
                        current_end = line_no
                        current_count = 1
                    else:
                        current_end = line_no
                        current_count += 1
                else:
                    if current_count >= min_size and current_start is not None and current_end is not None:
                        ranges.append(LineRange(
                            path=file_path,
                            start_line=current_start,
                            end_line=current_end,
                            line_count=current_count
                        ))
                    current_start = None
                    current_end = None
                    current_count = 0

            if current_count >= min_size and current_start is not None and current_end is not None:
                ranges.append(LineRange(
                    path=file_path,
                    start_line=current_start,
                    end_line=current_end,
                    line_count=current_count
                ))

        # Sort deterministically by line count descending, then path, then start_line
        ranges.sort(key=lambda r: (-r.line_count, r.path, r.start_line))
        return ranges[:top_k]

    def analyse_repository_path(
        self,
        git_dir: Path,
        repo_name: str,
        relation: str,
        student: StudentIdentity
    ) -> OwnershipAnalysisResult:
        """
        Performs the complete ownership analysis on an already cloned bare repository directory.
        Separated for deterministic unit testing and production execution.
        """
        start_time = time.time()
        notes: List[str] = []

        # 1. Verify shallow status
        if GitBlameRunner.is_shallow(git_dir):
            return OwnershipAnalysisResult(
                repo=repo_name,
                relation=relation,
                head_sha="UNKNOWN",
                method="git_blame_full_history",
                coverage=0.0,
                files_total=0,
                files_analysed=0,
                files_skipped=0,
                skipped_reasons={"shallow_repository": 1},
                student_lines=0.0,
                other_lines=0.0,
                unknown_lines=0.0,
                bot_lines=0.0,
                total_meaningful_lines=0.0,
                student_share=0.0,
                other_share=0.0,
                unknown_share=0.0,
                incomplete=True,
                solo_exception_applied=False,
                notes=["Repository is shallow. Ownership attribution requires full history."],
                skill_results=[],
                file_results=[],
                execution_time_sec=time.time() - start_time,
                status="SHALLOW_REJECTED",
                error_message="Shallow clone rejected"
            )

        head_sha = GitBlameRunner.get_head_sha(git_dir)

        # 2. Discover HEAD blobs
        all_blobs = GitBlameRunner.list_blobs(git_dir)
        total_blobs_count = len(all_blobs)

        candidate_blobs: List[Tuple[str, int]] = []
        skipped_reasons: Dict[str, int] = {}
        total_eligible_bytes = 0

        for file_path, size_bytes in all_blobs:
            # Check path exclusions
            skip, reason = should_skip_path(file_path)
            if skip:
                skipped_reasons[reason] = skipped_reasons.get(reason, 0) + 1
                continue

            # Check file size limit
            if size_bytes > MAX_FILE_SIZE_BYTES:
                skipped_reasons["oversized"] = skipped_reasons.get("oversized", 0) + 1
                continue

            candidate_blobs.append((file_path, size_bytes))
            total_eligible_bytes += size_bytes

        # Sort candidate files deterministically by path
        candidate_blobs.sort(key=lambda x: x[0])

        # Cap eligible files at MAX_SOURCE_FILES
        analysed_blobs = candidate_blobs[:MAX_SOURCE_FILES]
        if len(candidate_blobs) > MAX_SOURCE_FILES:
            skipped_count = len(candidate_blobs) - MAX_SOURCE_FILES
            skipped_reasons["source_file_cap_exceeded"] = skipped_count

        analysed_bytes = sum(size for _, size in analysed_blobs)
        coverage = (analysed_bytes / total_eligible_bytes) if total_eligible_bytes > 0 else 1.0

        # 3. Analyze commit history for solo exception check
        commit_authors_summary = GitBlameRunner.get_commit_authors_summary(git_dir, MAX_COMMITS)
        is_solo_eligible = self.evaluate_solo_repository_exception(
            repo_name=repo_name,
            relation=relation,
            student=student,
            commit_authors_summary=commit_authors_summary
        )

        # 4. Perform Git blame on each selected file
        file_results: List[FileOwnershipResult] = []
        file_blames_for_ranges: List[Tuple[str, List[dict], List[float]]] = []

        total_student_lines = 0.0
        total_other_lines = 0.0
        total_unknown_lines = 0.0
        total_bot_lines = 0.0
        total_meaningful_lines = 0.0

        skill_aggregates: Dict[str, Dict[str, float]] = {}

        # Collect distinct commit SHAs across all blames to batch fetch commit messages
        all_blame_data: List[Tuple[str, int, List[dict]]] = []
        needed_commit_shas: Set[str] = set()

        for file_path, size_bytes in analysed_blobs:
            blame_lines = GitBlameRunner.blame_file(
                git_dir, file_path, timeout_sec=MAX_FILE_BLAME_TIMEOUT_SEC
            )
            if blame_lines is None:
                skipped_reasons["blame_error"] = skipped_reasons.get("blame_error", 0) + 1
                continue

            # Check generated file and line length criteria
            raw_file_lines = [entry.get("line_content", "") for entry in blame_lines]
            is_gen, gen_reason = check_generated_and_line_length(raw_file_lines)
            if is_gen:
                skipped_reasons[gen_reason] = skipped_reasons.get(gen_reason, 0) + 1
                continue

            for entry in blame_lines:
                c_sha = entry.get("commit_sha", "")
                if c_sha:
                    needed_commit_shas.add(c_sha)

            all_blame_data.append((file_path, size_bytes, blame_lines))

        # Batch fetch commit messages for co-authored-by analysis
        commit_messages = GitBlameRunner.get_commit_messages(git_dir, needed_commit_shas)

        # 5. Process blame lines with anti-padding and co-authorship splitting
        for file_path, size_bytes, blame_lines in all_blame_data:
            p = Path(file_path)
            ext = p.suffix.lower()
            file_skills = self.map_file_to_skills(file_path)

            file_student = 0.0
            file_other = 0.0
            file_unknown = 0.0
            file_bot = 0.0
            file_meaningful = 0

            # Anti-padding tracking: per author, count of normalized line text in this file
            line_padding_counts: Dict[Tuple[str, str], int] = {}
            per_line_student_shares: List[float] = []

            for entry in blame_lines:
                raw_content = entry.get("line_content", "")
                c_sha = entry.get("commit_sha", "")
                author_mail = entry.get("author_mail", "")
                author_name = entry.get("author_name", "")
                c_msg = commit_messages.get(c_sha, "")

                if not is_meaningful_line(raw_content, ext):
                    per_line_student_shares.append(0.0)
                    continue

                # Anti-padding rule: count at most 3 times per author per file
                norm_line = raw_content.strip()
                author_key = f"{author_name.lower()}:{author_mail.lower()}"
                pad_key = (author_key, norm_line)
                count_seen = line_padding_counts.get(pad_key, 0)
                if count_seen >= 3:
                    per_line_student_shares.append(0.0)
                    continue
                line_padding_counts[pad_key] = count_seen + 1

                file_meaningful += 1

                # Resolve co-authored attribution
                attributions = IdentityResolver.resolve_commit_attribution(
                    primary_email=author_mail,
                    primary_name=author_name,
                    commit_message=c_msg,
                    student_identity=student
                )

                line_student_fraction = 0.0

                for category, fraction in attributions:
                    if category == AuthorCategory.STUDENT:
                        file_student += fraction
                        line_student_fraction += fraction
                    elif category == AuthorCategory.OTHER_HUMAN:
                        file_other += fraction
                    elif category == AuthorCategory.BOT:
                        file_bot += fraction
                    elif category == AuthorCategory.UNKNOWN:
                        file_unknown += fraction

                per_line_student_shares.append(line_student_fraction)

            file_blames_for_ranges.append((file_path, blame_lines, per_line_student_shares))

            # File level share (excluding bots from denominator)
            file_human_lines = file_student + file_other + file_unknown
            f_share = (file_student / file_human_lines) if file_human_lines > 0 else 0.0

            file_res = FileOwnershipResult(
                path=file_path,
                size_bytes=size_bytes,
                raw_lines=len(blame_lines),
                meaningful_lines=file_meaningful,
                student_lines=round(file_student, 2),
                other_lines=round(file_other, 2),
                bot_lines=round(file_bot, 2),
                unknown_lines=round(file_unknown, 2),
                student_share=round(f_share, 4),
                skills=file_skills
            )
            file_results.append(file_res)

            # Global aggregation
            total_student_lines += file_student
            total_other_lines += file_other
            total_unknown_lines += file_unknown
            total_bot_lines += file_bot
            total_meaningful_lines += file_meaningful

            # Skill-level aggregation
            for sk in file_skills:
                if sk not in skill_aggregates:
                    skill_aggregates[sk] = {
                        "student": 0.0,
                        "other": 0.0,
                        "unknown": 0.0,
                        "total_meaningful": 0.0
                    }
                skill_aggregates[sk]["student"] += file_student
                skill_aggregates[sk]["other"] += file_other
                skill_aggregates[sk]["unknown"] += file_unknown
                skill_aggregates[sk]["total_meaningful"] += file_meaningful

        # 6. Apply Solo-Owned Repository Exception or Conservative Unknown Handling
        solo_applied = False
        human_lines = total_student_lines + total_other_lines + total_unknown_lines
        unknown_ratio = (total_unknown_lines / human_lines) if human_lines > 0 else 0.0

        if is_solo_eligible:
            solo_applied = True
            total_student_lines += total_unknown_lines
            total_unknown_lines = 0.0
            notes.append("Solo-owned repository exception applied: unlinked commits attributed to student.")
        else:
            if unknown_ratio > 0.30:
                notes.append("Attribution incomplete — some commit identities could not be resolved.")

        # Recalculate shares
        human_lines_final = total_student_lines + total_other_lines + total_unknown_lines
        if human_lines_final > 0:
            student_share = total_student_lines / human_lines_final
            other_share = total_other_lines / human_lines_final
            unknown_share = total_unknown_lines / human_lines_final
        else:
            student_share = 0.0
            other_share = 0.0
            unknown_share = 0.0

        incomplete = (unknown_ratio > 0.30) and not solo_applied

        # 7. Build Skill Results with Top Ranges
        skill_results: List[SkillOwnershipResult] = []
        for skill_name in sorted(skill_aggregates.keys()):
            agg = skill_aggregates[skill_name]
            s_student = agg["student"]
            s_other = agg["other"]
            s_unknown = agg["unknown"]

            if solo_applied:
                s_student += s_unknown
                s_unknown = 0.0

            s_human = s_student + s_other + s_unknown
            s_share = (s_student / s_human) if s_human > 0 else 0.0

            top_ranges = self.extract_top_ranges_for_skill(
                file_blames=file_blames_for_ranges,
                target_skill=skill_name,
                min_size=MIN_RANGE_SIZE,
                top_k=5
            )

            skill_results.append(SkillOwnershipResult(
                skill=skill_name,
                student_lines=round(s_student, 2),
                other_lines=round(s_other, 2),
                unknown_lines=round(s_unknown, 2),
                total_meaningful_lines=round(s_human, 2),
                student_share=round(s_share, 4),
                top_ranges=top_ranges
            ))

        # Sort file results deterministically by path
        file_results.sort(key=lambda f: f.path)

        exec_time = time.time() - start_time

        return OwnershipAnalysisResult(
            repo=repo_name,
            relation=relation,
            head_sha=head_sha,
            method="git_blame_full_history",
            coverage=round(coverage, 4),
            files_total=total_blobs_count,
            files_analysed=len(file_results),
            files_skipped=sum(skipped_reasons.values()),
            skipped_reasons=skipped_reasons,
            student_lines=round(total_student_lines, 2),
            other_lines=round(total_other_lines, 2),
            unknown_lines=round(total_unknown_lines, 2),
            bot_lines=round(total_bot_lines, 2),
            total_meaningful_lines=round(total_meaningful_lines, 2),
            student_share=round(student_share, 4),
            other_share=round(other_share, 4),
            unknown_share=round(unknown_share, 4),
            incomplete=incomplete,
            solo_exception_applied=solo_applied,
            notes=notes,
            skill_results=skill_results,
            file_results=file_results,
            execution_time_sec=round(exec_time, 3),
            status="SUCCESS"
        )

    def analyse_repository(
        self,
        repo_identifier: str,
        student_identity: StudentIdentity,
        relation: str = "owner",
        timeout_sec: int = MAX_REPO_TIMEOUT_SEC
    ) -> OwnershipAnalysisResult:
        """
        Safe entry point for analyzing a remote repository by owner/repo.
        Clones bare repository safely into a temporary directory, executes analysis,
        and cleanly removes temporary files.
        """
        # Strict format validation
        if not validate_repo_identifier(repo_identifier):
            return OwnershipAnalysisResult(
                repo=repo_identifier,
                relation=relation,
                head_sha="UNKNOWN",
                method="git_blame_full_history",
                coverage=0.0,
                files_total=0,
                files_analysed=0,
                files_skipped=0,
                skipped_reasons={"invalid_repo_name": 1},
                student_lines=0.0,
                other_lines=0.0,
                unknown_lines=0.0,
                bot_lines=0.0,
                total_meaningful_lines=0.0,
                student_share=0.0,
                other_share=0.0,
                unknown_share=0.0,
                incomplete=True,
                solo_exception_applied=False,
                notes=["Invalid repository identifier format. Must match 'owner/repo'."],
                skill_results=[],
                file_results=[],
                execution_time_sec=0.0,
                status="ERROR",
                error_message="Invalid repository identifier"
            )

        with tempfile.TemporaryDirectory() as tmpdir:
            bare_dir = Path(tmpdir) / "repo.git"

            # Execute bare clone
            cloned = GitBlameRunner.clone_bare(
                repo_full_name=repo_identifier,
                dest_dir=bare_dir,
                timeout_sec=timeout_sec,
                token=self.github_token
            )
            if not cloned or not bare_dir.exists():
                return OwnershipAnalysisResult(
                    repo=repo_identifier,
                    relation=relation,
                    head_sha="UNKNOWN",
                    method="git_blame_full_history",
                    coverage=0.0,
                    files_total=0,
                    files_analysed=0,
                    files_skipped=0,
                    skipped_reasons={"clone_failed": 1},
                    student_lines=0.0,
                    other_lines=0.0,
                    unknown_lines=0.0,
                    bot_lines=0.0,
                    total_meaningful_lines=0.0,
                    student_share=0.0,
                    other_share=0.0,
                    unknown_share=0.0,
                    incomplete=True,
                    solo_exception_applied=False,
                    notes=["Failed to execute safe bare clone."],
                    skill_results=[],
                    file_results=[],
                    execution_time_sec=0.0,
                    status="ERROR",
                    error_message="Bare clone failed"
                )

            return self.analyse_repository_path(
                git_dir=bare_dir,
                repo_name=repo_identifier,
                relation=relation,
                student=student_identity
            )
