from enum import Enum


class LeetCodeCapability(str, Enum):
    PROFILE_STATS = "PROFILE_STATS"
    DIFFICULTY_STATS = "DIFFICULTY_STATS"
    LANGUAGE_STATS = "LANGUAGE_STATS"
    TOPIC_STATS = "TOPIC_STATS"
    QUESTION_LEVEL_DATA = "QUESTION_LEVEL_DATA"
    SUBMISSION_HISTORY = "SUBMISSION_HISTORY"
    CONTEST_HISTORY = "CONTEST_HISTORY"
    HISTORICAL_SNAPSHOTS = "HISTORICAL_SNAPSHOTS"
